compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

supportedArchitectures:
  cpu:
    - current
    - x64
    - ia32
    - arm64
  libc:
    - current
    - glibc
    - musl
  os:
    - current
    - win32
    - linux

yarnPath: .yarn/releases/yarn-4.0.2.cjs
